/**
 * List Gemini models available for the project's API keys.
 * Run: npx tsx ops/list-gemini-models.ts
 * Writes snapshot: docs/features/09-ai-notifications/gemini-models-snapshot.md
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';
import {
	getConfiguredSlots,
	resolveSecret,
} from '../server/config/gemini-keys';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

dotenv.config({ path: path.join(root, '.env') });

type GeminiModel = {
	name: string;
	displayName?: string;
	description?: string;
	inputTokenLimit?: number;
	outputTokenLimit?: number;
	supportedGenerationMethods?: string[];
};

type ListModelsResponse = {
	models?: GeminiModel[];
};

function collectExtraKeys(): { label: string; key: string }[] {
	const extras: { label: string; key: string }[] = [];
	for (const [envKey, value] of Object.entries(process.env)) {
		if (!value?.trim()) continue;
		if (/^GOOGLE_API_KEY_\d+$/.test(envKey)) {
			extras.push({ label: envKey, key: value.trim() });
		}
	}
	return extras.sort((a, b) => a.label.localeCompare(b.label, undefined, { numeric: true }));
}

async function fetchModels(apiKey: string): Promise<GeminiModel[]> {
	const url = `https://generativelanguage.googleapis.com/v1beta/models?key=${encodeURIComponent(apiKey)}&pageSize=100`;
	const res = await fetch(url);
	if (!res.ok) {
		const body = await res.text();
		throw new Error(`HTTP ${res.status}: ${body.slice(0, 300)}`);
	}
	const data = (await res.json()) as ListModelsResponse;
	return data.models ?? [];
}

function shortName(fullName: string): string {
	return fullName.replace(/^models\//, '');
}

function supportsGenerateContent(model: GeminiModel): boolean {
	return (model.supportedGenerationMethods ?? []).includes('generateContent');
}

async function smokeGenerate(apiKey: string, modelId: string): Promise<{ ok: boolean; detail: string }> {
	const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelId}:generateContent?key=${encodeURIComponent(apiKey)}`;
	try {
		const res = await fetch(url, {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({
				contents: [{ role: 'user', parts: [{ text: 'Reply with exactly: OK' }] }],
				generationConfig: { maxOutputTokens: 16 },
			}),
		});
		if (!res.ok) {
			return { ok: false, detail: `${res.status} ${(await res.text()).slice(0, 120)}` };
		}
		return { ok: true, detail: 'OK' };
	} catch (e) {
		return { ok: false, detail: e instanceof Error ? e.message : String(e) };
	}
}

async function main() {
	const slots = getConfiguredSlots();
	const extras = collectExtraKeys();
	const keyEntries: { label: string; key: string }[] = [
		...slots.map(({ slot, secret }) => ({
			label: `GEMINI_API_KEY_${slot}`,
			key: secret,
		})),
		...extras,
	];

	if (keyEntries.length === 0) {
		console.error('No GEMINI_API_KEY_* or GOOGLE_API_KEY_* found in .env');
		process.exit(1);
	}

	const primary = keyEntries[0];
	console.log(`Fetching models with ${primary.label}...`);
	const allModels = await fetchModels(primary.key);
	const chatModels = allModels
		.filter(supportsGenerateContent)
		.map((m) => ({
			...m,
			id: shortName(m.name),
		}))
		.sort((a, b) => a.id.localeCompare(b.id));

	console.log(`\nFound ${chatModels.length} models with generateContent support.\n`);

	const currentConfig = [
		'gemini-2.5-flash',
		'gemini-2.5-flash-lite',
		'gemini-3.1-flash-lite',
	];
	const candidates = [
		'gemini-2.5-flash',
		'gemini-2.5-flash-lite',
		'gemini-2.5-pro',
		'gemini-3.1-flash-lite',
		'gemini-3.5-flash-lite',
		'gemini-3.5-flash',
		'gemini-3.6-flash',
		'gemini-3.1-pro-preview',
		'gemini-3.1-flash',
	];

	const smokeResults: { id: string; listed: boolean; smoke: string }[] = [];
	for (const id of candidates) {
		const listed = chatModels.some((m) => m.id === id);
		if (!listed) {
			smokeResults.push({ id, listed: false, smoke: 'not listed' });
			continue;
		}
		const smoke = await smokeGenerate(primary.key, id);
		smokeResults.push({
			id,
			listed: true,
			smoke: smoke.ok ? 'pass' : `fail: ${smoke.detail}`,
		});
		console.log(`smoke ${id}: ${smoke.ok ? 'pass' : smoke.detail}`);
	}

	const now = new Date().toISOString();
	const lines: string[] = [
		'# Gemini Models Snapshot',
		'',
		'> Auto-generated by `ops/list-gemini-models.ts`. Do not hand-edit the tables below.',
		'',
		`| Generated | ${now} |`,
		`| Primary key slot | ${primary.label} |`,
		`| Total generateContent models | ${chatModels.length} |`,
		'',
		'## Current config (`server/config/gemini-config.ts`)',
		'',
		...currentConfig.map((m) => `- \`${m}\``),
		'',
		'## Smoke test (primary key)',
		'',
		'| Model ID | Listed | Smoke generateContent |',
		'|----------|--------|-------------------------|',
		...smokeResults.map(
			(r) => `| \`${r.id}\` | ${r.listed ? 'yes' : 'no'} | ${r.smoke} |`,
		),
		'',
		'## All models (generateContent)',
		'',
		'| Model ID | Display name | Input limit |',
		'|----------|--------------|-------------|',
		...chatModels.map(
			(m) =>
				`| \`${m.id}\` | ${m.displayName ?? '—'} | ${m.inputTokenLimit ?? '—'} |`,
		),
		'',
	];

	const outPath = path.join(
		root,
		'docs/features/09-ai-notifications/gemini-models-snapshot.md',
	);
	fs.mkdirSync(path.dirname(outPath), { recursive: true });
	fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
	console.log(`\nWrote ${outPath}`);
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
